### ISSUE TITLE
Install on/boot from SD Card

### ISSUE THREAD

**Issue by netstx** [AshyIsMe/openbsd-rpi4#1]
Is it possible to install OpenBSD on the SD Card and then boot from it? I am assuming the UEFI firmware still has to be loaded at boot via an USB drive in this case? Thanks!

**Comment by AshyIsMe** [comment]
I think it's possible, haven't tested it yet though.

The UEFI can definitely be on an sdcard.

**Comment by netstx** [comment]
Sounds good. Do you have any pointers as far as getting OpenBSD to boot without the additional SD/USB? I imagine the firmware has to be on the boot partition, but not sure how that works. I'd be willing to try, just don't know where to start...

**Comment by AshyIsMe** [comment]
I think the miniroot68.img has a suitable fat partition that you could copy the uefi files onto so that would be where I would start.

* Make an openbsd miniroot68 sdcard as per the instructions
* Try to copy the uefi files onto the boot partition as per uefi instructions
* Try to boot

Alternatively if you do have a cheap spare usb stick lying around you only need that for the install process.  You can partition up the sdcard so it has a uefi partition and the rest of it is partitioned for the openbsd root install.

**Comment by netstx** [comment]
Thanks, I will give that a try. If I have any success, I will post here :)

**Comment by netstx** [comment]
@AshyIsMe I just found this reddit thread: https://www.reddit.com/r/openbsd/comments/mry6vz/booting_on_raspberry_pi_4_from_sd_card/ - looks like on 6.9 it will be possible to install openbsd without having to use the UEFI firmware :)

**Comment by AshyIsMe** [comment]
Ah that's great, I look forward to this repo being obsolete :)

**Comment by netstx** [comment]
I sent a PR to update the README to let folks now :)
